version: 2.1
publish-github-release:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      # build Docker image
      - run: docker build -t trigrab/vs-resinvessel:$CIRCLE_BRANCH .
      - run: docker run trigrab/vs-resinvessel:$CIRCLE_BRANCH ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./resinvessel.dll