version: 2.1
jobs:
  publish-github-release:
   machine: true
   steps:
      - checkout

      # build Docker image
      - run: docker build -t trigrab/vs-resinvessel:$CIRCLE_BRANCH .
      - run: docker run trigrab/vs-resinvessel:$CIRCLE_BRANCH ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./resinvessel.dll